# fly.toml app configuration file generated for auf-team on 2025-05-24T08:32:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'auf-team'
primary_region = 'arn'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 4096
