# fly.toml app configuration file generated for auf-team on 2025-05-24T07:57:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'auf-team'
primary_region = 'arn'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
